Ingredient.create!(name: "Limão")
Ingredient.create!(name: "Gelo")
Ingredient.create!(name: "Menta")
Ingredient.create!(name: "Suco de laranja")
Ingredient.create!(name: "Coca cola")
Ingredient.create!(name: "Vodka")
Ingredient.create!(name: "Cachaça")
Ingredient.create!(name: "Tequila")
Ingredient.create!(name: "Açucar")
Ingredient.create!(name: "Hortelã")
Ingredient.create!(name: "Maracujá")
Ingredient.create!(name: "Água com gás")
